/**
 * This class is generated by jOOQ
 */
package sxj.db.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import sxj.db.tables.Course;
import sxj.db.tables.records.CourseRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class CourseDao extends DAOImpl<CourseRecord, sxj.db.tables.pojos.Course, Integer> {

    /**
     * Create a new CourseDao without any configuration
     */
    public CourseDao() {
        super(Course.COURSE, sxj.db.tables.pojos.Course.class);
    }

    /**
     * Create a new CourseDao with an attached configuration
     */
    @Autowired
    public CourseDao(Configuration configuration) {
        super(Course.COURSE, sxj.db.tables.pojos.Course.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(sxj.db.tables.pojos.Course object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<sxj.db.tables.pojos.Course> fetchById(Integer... values) {
        return fetch(Course.COURSE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public sxj.db.tables.pojos.Course fetchOneById(Integer value) {
        return fetchOne(Course.COURSE.ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<sxj.db.tables.pojos.Course> fetchByName(String... values) {
        return fetch(Course.COURSE.NAME, values);
    }

    /**
     * Fetch records that have <code>type IN (values)</code>
     */
    public List<sxj.db.tables.pojos.Course> fetchByType(String... values) {
        return fetch(Course.COURSE.TYPE, values);
    }

    /**
     * Fetch records that have <code>clazz_id IN (values)</code>
     */
    public List<sxj.db.tables.pojos.Course> fetchByClazzId(Integer... values) {
        return fetch(Course.COURSE.CLAZZ_ID, values);
    }

    /**
     * Fetch records that have <code>weight IN (values)</code>
     */
    public List<sxj.db.tables.pojos.Course> fetchByWeight(Double... values) {
        return fetch(Course.COURSE.WEIGHT, values);
    }

    /**
     * Fetch records that have <code>code IN (values)</code>
     */
    public List<sxj.db.tables.pojos.Course> fetchByCode(String... values) {
        return fetch(Course.COURSE.CODE, values);
    }

    /**
     * Fetch records that have <code>normal_percent IN (values)</code>
     */
    public List<sxj.db.tables.pojos.Course> fetchByNormalPercent(Double... values) {
        return fetch(Course.COURSE.NORMAL_PERCENT, values);
    }

    /**
     * Fetch records that have <code>terminal_percent IN (values)</code>
     */
    public List<sxj.db.tables.pojos.Course> fetchByTerminalPercent(Double... values) {
        return fetch(Course.COURSE.TERMINAL_PERCENT, values);
    }
}
