/**
 * This class is generated by jOOQ
 */
package sxj.db.tables.daos;


import java.util.Date;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import sxj.db.tables.EmailInfo;
import sxj.db.tables.records.EmailInfoRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class EmailInfoDao extends DAOImpl<EmailInfoRecord, sxj.db.tables.pojos.EmailInfo, Integer> {

    /**
     * Create a new EmailInfoDao without any configuration
     */
    public EmailInfoDao() {
        super(EmailInfo.EMAIL_INFO, sxj.db.tables.pojos.EmailInfo.class);
    }

    /**
     * Create a new EmailInfoDao with an attached configuration
     */
    @Autowired
    public EmailInfoDao(Configuration configuration) {
        super(EmailInfo.EMAIL_INFO, sxj.db.tables.pojos.EmailInfo.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(sxj.db.tables.pojos.EmailInfo object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<sxj.db.tables.pojos.EmailInfo> fetchById(Integer... values) {
        return fetch(EmailInfo.EMAIL_INFO.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public sxj.db.tables.pojos.EmailInfo fetchOneById(Integer value) {
        return fetchOne(EmailInfo.EMAIL_INFO.ID, value);
    }

    /**
     * Fetch records that have <code>sender IN (values)</code>
     */
    public List<sxj.db.tables.pojos.EmailInfo> fetchBySender(String... values) {
        return fetch(EmailInfo.EMAIL_INFO.SENDER, values);
    }

    /**
     * Fetch records that have <code>receiver IN (values)</code>
     */
    public List<sxj.db.tables.pojos.EmailInfo> fetchByReceiver(String... values) {
        return fetch(EmailInfo.EMAIL_INFO.RECEIVER, values);
    }

    /**
     * Fetch records that have <code>context IN (values)</code>
     */
    public List<sxj.db.tables.pojos.EmailInfo> fetchByContext(String... values) {
        return fetch(EmailInfo.EMAIL_INFO.CONTEXT, values);
    }

    /**
     * Fetch records that have <code>code IN (values)</code>
     */
    public List<sxj.db.tables.pojos.EmailInfo> fetchByCode(String... values) {
        return fetch(EmailInfo.EMAIL_INFO.CODE, values);
    }

    /**
     * Fetch records that have <code>subject IN (values)</code>
     */
    public List<sxj.db.tables.pojos.EmailInfo> fetchBySubject(String... values) {
        return fetch(EmailInfo.EMAIL_INFO.SUBJECT, values);
    }

    /**
     * Fetch records that have <code>send_date IN (values)</code>
     */
    public List<sxj.db.tables.pojos.EmailInfo> fetchBySendDate(Date... values) {
        return fetch(EmailInfo.EMAIL_INFO.SEND_DATE, values);
    }

    /**
     * Fetch records that have <code>ip IN (values)</code>
     */
    public List<sxj.db.tables.pojos.EmailInfo> fetchByIp(String... values) {
        return fetch(EmailInfo.EMAIL_INFO.IP, values);
    }
}
