/**
 * This class is generated by jOOQ
 */
package sxj.db.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import sxj.db.tables.OrderItem;
import sxj.db.tables.records.OrderItemRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class OrderItemDao extends DAOImpl<OrderItemRecord, sxj.db.tables.pojos.OrderItem, Integer> {

    /**
     * Create a new OrderItemDao without any configuration
     */
    public OrderItemDao() {
        super(OrderItem.ORDER_ITEM, sxj.db.tables.pojos.OrderItem.class);
    }

    /**
     * Create a new OrderItemDao with an attached configuration
     */
    @Autowired
    public OrderItemDao(Configuration configuration) {
        super(OrderItem.ORDER_ITEM, sxj.db.tables.pojos.OrderItem.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(sxj.db.tables.pojos.OrderItem object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<sxj.db.tables.pojos.OrderItem> fetchById(Integer... values) {
        return fetch(OrderItem.ORDER_ITEM.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public sxj.db.tables.pojos.OrderItem fetchOneById(Integer value) {
        return fetchOne(OrderItem.ORDER_ITEM.ID, value);
    }

    /**
     * Fetch records that have <code>imgs IN (values)</code>
     */
    public List<sxj.db.tables.pojos.OrderItem> fetchByImgs(String... values) {
        return fetch(OrderItem.ORDER_ITEM.IMGS, values);
    }

    /**
     * Fetch records that have <code>description IN (values)</code>
     */
    public List<sxj.db.tables.pojos.OrderItem> fetchByDescription(String... values) {
        return fetch(OrderItem.ORDER_ITEM.DESCRIPTION, values);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<sxj.db.tables.pojos.OrderItem> fetchByName(String... values) {
        return fetch(OrderItem.ORDER_ITEM.NAME, values);
    }

    /**
     * Fetch records that have <code>price IN (values)</code>
     */
    public List<sxj.db.tables.pojos.OrderItem> fetchByPrice(Double... values) {
        return fetch(OrderItem.ORDER_ITEM.PRICE, values);
    }

    /**
     * Fetch records that have <code>type IN (values)</code>
     */
    public List<sxj.db.tables.pojos.OrderItem> fetchByType(String... values) {
        return fetch(OrderItem.ORDER_ITEM.TYPE, values);
    }

    /**
     * Fetch records that have <code>order_id IN (values)</code>
     */
    public List<sxj.db.tables.pojos.OrderItem> fetchByOrderId(Integer... values) {
        return fetch(OrderItem.ORDER_ITEM.ORDER_ID, values);
    }
}
