/**
 * This class is generated by jOOQ
 */
package sxj.db.tables.daos;


import java.util.Date;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import sxj.db.tables.User;
import sxj.db.tables.records.UserRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class UserDao extends DAOImpl<UserRecord, sxj.db.tables.pojos.User, Integer> {

    /**
     * Create a new UserDao without any configuration
     */
    public UserDao() {
        super(User.USER, sxj.db.tables.pojos.User.class);
    }

    /**
     * Create a new UserDao with an attached configuration
     */
    @Autowired
    public UserDao(Configuration configuration) {
        super(User.USER, sxj.db.tables.pojos.User.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(sxj.db.tables.pojos.User object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<sxj.db.tables.pojos.User> fetchById(Integer... values) {
        return fetch(User.USER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public sxj.db.tables.pojos.User fetchOneById(Integer value) {
        return fetchOne(User.USER.ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<sxj.db.tables.pojos.User> fetchByName(String... values) {
        return fetch(User.USER.NAME, values);
    }

    /**
     * Fetch records that have <code>password IN (values)</code>
     */
    public List<sxj.db.tables.pojos.User> fetchByPassword(String... values) {
        return fetch(User.USER.PASSWORD, values);
    }

    /**
     * Fetch records that have <code>telephone IN (values)</code>
     */
    public List<sxj.db.tables.pojos.User> fetchByTelephone(String... values) {
        return fetch(User.USER.TELEPHONE, values);
    }

    /**
     * Fetch records that have <code>imgs IN (values)</code>
     */
    public List<sxj.db.tables.pojos.User> fetchByImgs(String... values) {
        return fetch(User.USER.IMGS, values);
    }

    /**
     * Fetch records that have <code>last_login_date IN (values)</code>
     */
    public List<sxj.db.tables.pojos.User> fetchByLastLoginDate(Date... values) {
        return fetch(User.USER.LAST_LOGIN_DATE, values);
    }

    /**
     * Fetch records that have <code>register_date IN (values)</code>
     */
    public List<sxj.db.tables.pojos.User> fetchByRegisterDate(Date... values) {
        return fetch(User.USER.REGISTER_DATE, values);
    }

    /**
     * Fetch records that have <code>email IN (values)</code>
     */
    public List<sxj.db.tables.pojos.User> fetchByEmail(String... values) {
        return fetch(User.USER.EMAIL, values);
    }

    /**
     * Fetch records that have <code>role IN (values)</code>
     */
    public List<sxj.db.tables.pojos.User> fetchByRole(String... values) {
        return fetch(User.USER.ROLE, values);
    }
}
