/**
 * This class is generated by jOOQ
 */
package sxj.db.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import sxj.db.tables.File;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FileRecord extends UpdatableRecordImpl<FileRecord> implements Record5<Integer, String, String, Integer, Integer> {

    private static final long serialVersionUID = 1987048759;

    /**
     * Setter for <code>test.file.id</code>.
     */
    public FileRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>test.file.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>test.file.file_name</code>. 文件名
     */
    public FileRecord setFileName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>test.file.file_name</code>. 文件名
     */
    public String getFileName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>test.file.file_url</code>. 文件url
     */
    public FileRecord setFileUrl(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>test.file.file_url</code>. 文件url
     */
    public String getFileUrl() {
        return (String) get(2);
    }

    /**
     * Setter for <code>test.file.source</code>. 1.order，2.product
     */
    public FileRecord setSource(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>test.file.source</code>. 1.order，2.product
     */
    public Integer getSource() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>test.file.source_id</code>. 父id
     */
    public FileRecord setSourceId(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>test.file.source_id</code>. 父id
     */
    public Integer getSourceId() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, String, Integer, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, String, Integer, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return File.FILE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return File.FILE.FILE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return File.FILE.FILE_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return File.FILE.SOURCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return File.FILE.SOURCE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getFileName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getFileUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getSource();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getSourceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FileRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FileRecord value2(String value) {
        setFileName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FileRecord value3(String value) {
        setFileUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FileRecord value4(Integer value) {
        setSource(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FileRecord value5(Integer value) {
        setSourceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FileRecord values(Integer value1, String value2, String value3, Integer value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FileRecord
     */
    public FileRecord() {
        super(File.FILE);
    }

    /**
     * Create a detached, initialised FileRecord
     */
    public FileRecord(Integer id, String fileName, String fileUrl, Integer source, Integer sourceId) {
        super(File.FILE);

        set(0, id);
        set(1, fileName);
        set(2, fileUrl);
        set(3, source);
        set(4, sourceId);
    }
}
