/**
 * This class is generated by jOOQ
 */
package sxj.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Course implements Serializable {

    private static final long serialVersionUID = -1245543620;

    private Integer id;
    private String  name;
    private String  type;
    private Integer clazzId;
    private Double  weight;
    private String  code;
    private Double  normalPercent;
    private Double  terminalPercent;

    public Course() {}

    public Course(Course value) {
        this.id = value.id;
        this.name = value.name;
        this.type = value.type;
        this.clazzId = value.clazzId;
        this.weight = value.weight;
        this.code = value.code;
        this.normalPercent = value.normalPercent;
        this.terminalPercent = value.terminalPercent;
    }

    public Course(
        Integer id,
        String  name,
        String  type,
        Integer clazzId,
        Double  weight,
        String  code,
        Double  normalPercent,
        Double  terminalPercent
    ) {
        this.id = id;
        this.name = name;
        this.type = type;
        this.clazzId = clazzId;
        this.weight = weight;
        this.code = code;
        this.normalPercent = normalPercent;
        this.terminalPercent = terminalPercent;
    }

    public Integer getId() {
        return this.id;
    }

    public Course setId(Integer id) {
        this.id = id;
        return this;
    }

    public String getName() {
        return this.name;
    }

    public Course setName(String name) {
        this.name = name;
        return this;
    }

    public String getType() {
        return this.type;
    }

    public Course setType(String type) {
        this.type = type;
        return this;
    }

    public Integer getClazzId() {
        return this.clazzId;
    }

    public Course setClazzId(Integer clazzId) {
        this.clazzId = clazzId;
        return this;
    }

    public Double getWeight() {
        return this.weight;
    }

    public Course setWeight(Double weight) {
        this.weight = weight;
        return this;
    }

    public String getCode() {
        return this.code;
    }

    public Course setCode(String code) {
        this.code = code;
        return this;
    }

    public Double getNormalPercent() {
        return this.normalPercent;
    }

    public Course setNormalPercent(Double normalPercent) {
        this.normalPercent = normalPercent;
        return this;
    }

    public Double getTerminalPercent() {
        return this.terminalPercent;
    }

    public Course setTerminalPercent(Double terminalPercent) {
        this.terminalPercent = terminalPercent;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Course other = (Course) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (name == null) {
            if (other.name != null)
                return false;
        }
        else if (!name.equals(other.name))
            return false;
        if (type == null) {
            if (other.type != null)
                return false;
        }
        else if (!type.equals(other.type))
            return false;
        if (clazzId == null) {
            if (other.clazzId != null)
                return false;
        }
        else if (!clazzId.equals(other.clazzId))
            return false;
        if (weight == null) {
            if (other.weight != null)
                return false;
        }
        else if (!weight.equals(other.weight))
            return false;
        if (code == null) {
            if (other.code != null)
                return false;
        }
        else if (!code.equals(other.code))
            return false;
        if (normalPercent == null) {
            if (other.normalPercent != null)
                return false;
        }
        else if (!normalPercent.equals(other.normalPercent))
            return false;
        if (terminalPercent == null) {
            if (other.terminalPercent != null)
                return false;
        }
        else if (!terminalPercent.equals(other.terminalPercent))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((id == null) ? 0 : id.hashCode());
        result = prime * result + ((name == null) ? 0 : name.hashCode());
        result = prime * result + ((type == null) ? 0 : type.hashCode());
        result = prime * result + ((clazzId == null) ? 0 : clazzId.hashCode());
        result = prime * result + ((weight == null) ? 0 : weight.hashCode());
        result = prime * result + ((code == null) ? 0 : code.hashCode());
        result = prime * result + ((normalPercent == null) ? 0 : normalPercent.hashCode());
        result = prime * result + ((terminalPercent == null) ? 0 : terminalPercent.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Course (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(type);
        sb.append(", ").append(clazzId);
        sb.append(", ").append(weight);
        sb.append(", ").append(code);
        sb.append(", ").append(normalPercent);
        sb.append(", ").append(terminalPercent);

        sb.append(")");
        return sb.toString();
    }
}
