/**
 * This class is generated by jOOQ
 */
package sxj.db.tables.pojos;


import java.io.Serializable;
import java.sql.Date;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Order implements Serializable {

    private static final long serialVersionUID = 1821848102;

    private Integer id;
    private String  name;
    private Double  totalPrice;
    private String  desc;
    private Date    date;

    public Order() {}

    public Order(Order value) {
        this.id = value.id;
        this.name = value.name;
        this.totalPrice = value.totalPrice;
        this.desc = value.desc;
        this.date = value.date;
    }

    public Order(
        Integer id,
        String  name,
        Double  totalPrice,
        String  desc,
        Date    date
    ) {
        this.id = id;
        this.name = name;
        this.totalPrice = totalPrice;
        this.desc = desc;
        this.date = date;
    }

    public Integer getId() {
        return this.id;
    }

    public Order setId(Integer id) {
        this.id = id;
        return this;
    }

    public String getName() {
        return this.name;
    }

    public Order setName(String name) {
        this.name = name;
        return this;
    }

    public Double getTotalPrice() {
        return this.totalPrice;
    }

    public Order setTotalPrice(Double totalPrice) {
        this.totalPrice = totalPrice;
        return this;
    }

    public String getDesc() {
        return this.desc;
    }

    public Order setDesc(String desc) {
        this.desc = desc;
        return this;
    }

    public Date getDate() {
        return this.date;
    }

    public Order setDate(Date date) {
        this.date = date;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Order other = (Order) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (name == null) {
            if (other.name != null)
                return false;
        }
        else if (!name.equals(other.name))
            return false;
        if (totalPrice == null) {
            if (other.totalPrice != null)
                return false;
        }
        else if (!totalPrice.equals(other.totalPrice))
            return false;
        if (desc == null) {
            if (other.desc != null)
                return false;
        }
        else if (!desc.equals(other.desc))
            return false;
        if (date == null) {
            if (other.date != null)
                return false;
        }
        else if (!date.equals(other.date))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((id == null) ? 0 : id.hashCode());
        result = prime * result + ((name == null) ? 0 : name.hashCode());
        result = prime * result + ((totalPrice == null) ? 0 : totalPrice.hashCode());
        result = prime * result + ((desc == null) ? 0 : desc.hashCode());
        result = prime * result + ((date == null) ? 0 : date.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Order (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(totalPrice);
        sb.append(", ").append(desc);
        sb.append(", ").append(date);

        sb.append(")");
        return sb.toString();
    }
}
