/**
 * This class is generated by jOOQ
 */
package sxj.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Question implements Serializable {

    private static final long serialVersionUID = -58689421;

    private Integer id;
    private String  num;
    private String  name;
    private Integer count;
    private Double  score;
    private Double  percent;
    private Double  ascore;
    private Integer countScore;
    private Integer courseId;
    private Integer normalTerminal;
    private String  proxml;

    public Question() {}

    public Question(Question value) {
        this.id = value.id;
        this.num = value.num;
        this.name = value.name;
        this.count = value.count;
        this.score = value.score;
        this.percent = value.percent;
        this.ascore = value.ascore;
        this.countScore = value.countScore;
        this.courseId = value.courseId;
        this.normalTerminal = value.normalTerminal;
        this.proxml = value.proxml;
    }

    public Question(
        Integer id,
        String  num,
        String  name,
        Integer count,
        Double  score,
        Double  percent,
        Double  ascore,
        Integer countScore,
        Integer courseId,
        Integer normalTerminal,
        String  proxml
    ) {
        this.id = id;
        this.num = num;
        this.name = name;
        this.count = count;
        this.score = score;
        this.percent = percent;
        this.ascore = ascore;
        this.countScore = countScore;
        this.courseId = courseId;
        this.normalTerminal = normalTerminal;
        this.proxml = proxml;
    }

    public Integer getId() {
        return this.id;
    }

    public Question setId(Integer id) {
        this.id = id;
        return this;
    }

    public String getNum() {
        return this.num;
    }

    public Question setNum(String num) {
        this.num = num;
        return this;
    }

    public String getName() {
        return this.name;
    }

    public Question setName(String name) {
        this.name = name;
        return this;
    }

    public Integer getCount() {
        return this.count;
    }

    public Question setCount(Integer count) {
        this.count = count;
        return this;
    }

    public Double getScore() {
        return this.score;
    }

    public Question setScore(Double score) {
        this.score = score;
        return this;
    }

    public Double getPercent() {
        return this.percent;
    }

    public Question setPercent(Double percent) {
        this.percent = percent;
        return this;
    }

    public Double getAscore() {
        return this.ascore;
    }

    public Question setAscore(Double ascore) {
        this.ascore = ascore;
        return this;
    }

    public Integer getCountScore() {
        return this.countScore;
    }

    public Question setCountScore(Integer countScore) {
        this.countScore = countScore;
        return this;
    }

    public Integer getCourseId() {
        return this.courseId;
    }

    public Question setCourseId(Integer courseId) {
        this.courseId = courseId;
        return this;
    }

    public Integer getNormalTerminal() {
        return this.normalTerminal;
    }

    public Question setNormalTerminal(Integer normalTerminal) {
        this.normalTerminal = normalTerminal;
        return this;
    }

    public String getProxml() {
        return this.proxml;
    }

    public Question setProxml(String proxml) {
        this.proxml = proxml;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Question other = (Question) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (num == null) {
            if (other.num != null)
                return false;
        }
        else if (!num.equals(other.num))
            return false;
        if (name == null) {
            if (other.name != null)
                return false;
        }
        else if (!name.equals(other.name))
            return false;
        if (count == null) {
            if (other.count != null)
                return false;
        }
        else if (!count.equals(other.count))
            return false;
        if (score == null) {
            if (other.score != null)
                return false;
        }
        else if (!score.equals(other.score))
            return false;
        if (percent == null) {
            if (other.percent != null)
                return false;
        }
        else if (!percent.equals(other.percent))
            return false;
        if (ascore == null) {
            if (other.ascore != null)
                return false;
        }
        else if (!ascore.equals(other.ascore))
            return false;
        if (countScore == null) {
            if (other.countScore != null)
                return false;
        }
        else if (!countScore.equals(other.countScore))
            return false;
        if (courseId == null) {
            if (other.courseId != null)
                return false;
        }
        else if (!courseId.equals(other.courseId))
            return false;
        if (normalTerminal == null) {
            if (other.normalTerminal != null)
                return false;
        }
        else if (!normalTerminal.equals(other.normalTerminal))
            return false;
        if (proxml == null) {
            if (other.proxml != null)
                return false;
        }
        else if (!proxml.equals(other.proxml))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((id == null) ? 0 : id.hashCode());
        result = prime * result + ((num == null) ? 0 : num.hashCode());
        result = prime * result + ((name == null) ? 0 : name.hashCode());
        result = prime * result + ((count == null) ? 0 : count.hashCode());
        result = prime * result + ((score == null) ? 0 : score.hashCode());
        result = prime * result + ((percent == null) ? 0 : percent.hashCode());
        result = prime * result + ((ascore == null) ? 0 : ascore.hashCode());
        result = prime * result + ((countScore == null) ? 0 : countScore.hashCode());
        result = prime * result + ((courseId == null) ? 0 : courseId.hashCode());
        result = prime * result + ((normalTerminal == null) ? 0 : normalTerminal.hashCode());
        result = prime * result + ((proxml == null) ? 0 : proxml.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Question (");

        sb.append(id);
        sb.append(", ").append(num);
        sb.append(", ").append(name);
        sb.append(", ").append(count);
        sb.append(", ").append(score);
        sb.append(", ").append(percent);
        sb.append(", ").append(ascore);
        sb.append(", ").append(countScore);
        sb.append(", ").append(courseId);
        sb.append(", ").append(normalTerminal);
        sb.append(", ").append(proxml);

        sb.append(")");
        return sb.toString();
    }
}
