/**
 * This class is generated by jOOQ
 */
package sxj.db.tables.pojos;


import java.io.Serializable;
import java.util.Date;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = 1925144131;

    private Integer id;
    private String  name;
    private String  password;
    private String  telephone;
    private String  imgs;
    private Date    lastLoginDate;
    private Date    registerDate;
    private String  email;
    private Integer deleted;
    private String  role;

    public User() {}

    public User(User value) {
        this.id = value.id;
        this.name = value.name;
        this.password = value.password;
        this.telephone = value.telephone;
        this.imgs = value.imgs;
        this.lastLoginDate = value.lastLoginDate;
        this.registerDate = value.registerDate;
        this.email = value.email;
        this.deleted = value.deleted;
        this.role = value.role;
    }

    public User(
        Integer id,
        String  name,
        String  password,
        String  telephone,
        String  imgs,
        Date    lastLoginDate,
        Date    registerDate,
        String  email,
        Integer deleted,
        String  role
    ) {
        this.id = id;
        this.name = name;
        this.password = password;
        this.telephone = telephone;
        this.imgs = imgs;
        this.lastLoginDate = lastLoginDate;
        this.registerDate = registerDate;
        this.email = email;
        this.deleted = deleted;
        this.role = role;
    }

    public Integer getId() {
        return this.id;
    }

    public User setId(Integer id) {
        this.id = id;
        return this;
    }

    public String getName() {
        return this.name;
    }

    public User setName(String name) {
        this.name = name;
        return this;
    }

    public String getPassword() {
        return this.password;
    }

    public User setPassword(String password) {
        this.password = password;
        return this;
    }

    public String getTelephone() {
        return this.telephone;
    }

    public User setTelephone(String telephone) {
        this.telephone = telephone;
        return this;
    }

    public String getImgs() {
        return this.imgs;
    }

    public User setImgs(String imgs) {
        this.imgs = imgs;
        return this;
    }

    public Date getLastLoginDate() {
        return this.lastLoginDate;
    }

    public User setLastLoginDate(Date lastLoginDate) {
        this.lastLoginDate = lastLoginDate;
        return this;
    }

    public Date getRegisterDate() {
        return this.registerDate;
    }

    public User setRegisterDate(Date registerDate) {
        this.registerDate = registerDate;
        return this;
    }

    public String getEmail() {
        return this.email;
    }

    public User setEmail(String email) {
        this.email = email;
        return this;
    }

    public Integer getDeleted() {
        return this.deleted;
    }

    public User setDeleted(Integer deleted) {
        this.deleted = deleted;
        return this;
    }

    public String getRole() {
        return this.role;
    }

    public User setRole(String role) {
        this.role = role;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final User other = (User) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (name == null) {
            if (other.name != null)
                return false;
        }
        else if (!name.equals(other.name))
            return false;
        if (password == null) {
            if (other.password != null)
                return false;
        }
        else if (!password.equals(other.password))
            return false;
        if (telephone == null) {
            if (other.telephone != null)
                return false;
        }
        else if (!telephone.equals(other.telephone))
            return false;
        if (imgs == null) {
            if (other.imgs != null)
                return false;
        }
        else if (!imgs.equals(other.imgs))
            return false;
        if (lastLoginDate == null) {
            if (other.lastLoginDate != null)
                return false;
        }
        else if (!lastLoginDate.equals(other.lastLoginDate))
            return false;
        if (registerDate == null) {
            if (other.registerDate != null)
                return false;
        }
        else if (!registerDate.equals(other.registerDate))
            return false;
        if (email == null) {
            if (other.email != null)
                return false;
        }
        else if (!email.equals(other.email))
            return false;
        if (deleted == null) {
            if (other.deleted != null)
                return false;
        }
        else if (!deleted.equals(other.deleted))
            return false;
        if (role == null) {
            if (other.role != null)
                return false;
        }
        else if (!role.equals(other.role))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((id == null) ? 0 : id.hashCode());
        result = prime * result + ((name == null) ? 0 : name.hashCode());
        result = prime * result + ((password == null) ? 0 : password.hashCode());
        result = prime * result + ((telephone == null) ? 0 : telephone.hashCode());
        result = prime * result + ((imgs == null) ? 0 : imgs.hashCode());
        result = prime * result + ((lastLoginDate == null) ? 0 : lastLoginDate.hashCode());
        result = prime * result + ((registerDate == null) ? 0 : registerDate.hashCode());
        result = prime * result + ((email == null) ? 0 : email.hashCode());
        result = prime * result + ((deleted == null) ? 0 : deleted.hashCode());
        result = prime * result + ((role == null) ? 0 : role.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(password);
        sb.append(", ").append(telephone);
        sb.append(", ").append(imgs);
        sb.append(", ").append(lastLoginDate);
        sb.append(", ").append(registerDate);
        sb.append(", ").append(email);
        sb.append(", ").append(deleted);
        sb.append(", ").append(role);

        sb.append(")");
        return sb.toString();
    }
}
