/**
 * This class is generated by jOOQ
 */
package com.dao;

import java.sql.Date;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Configuration;
import org.jooq.DSLContext;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;
import org.springframework.util.StringUtils;

import com.domain.Order;
import com.util.Paging;

import sxj.db.tables.records.OrderRecord;
import static sxj.db.Tables.ORDER;
import static sxj.db.Tables.PRODUCT;

@Repository
public class OrderDao extends DAOImpl<OrderRecord, Order, Integer> {

	@Autowired
	private DSLContext dslContext;

	public OrderDao(Configuration configuration) {
		super(ORDER, Order.class, configuration);
	}

	@Override
	protected Integer getId(Order order) {
		return order.getId();
	}

	/****************************************************
	 * 下面是自定义方法
	 ***************************************************************/

	public Order findOrderById(Integer id) {
		return dslContext.select().from(ORDER).fetchOneInto(Order.class);
	}
	/**
	 * 查询订单集合
	 * @param paging
	 * @return
	 */
	public Paging<Order> orderList(Paging<Order> paging) {
		Condition condition = null;
		String orderField;
		if (StringUtils.hasText(paging.getKeyword())) {
			condition = ORDER.NAME.like("%"+paging.getKeyword()+"%");
		}
		List<Order> list = dslContext.select().from(ORDER).where(condition).orderBy(ORDER.DATE.desc())
				.limit(paging.offset(), paging.getPageSize()).fetchInto(Order.class);
		int totalCount = dslContext.fetchCount(dslContext.select().from(ORDER).where(condition));
		
		paging.setTotalCount(totalCount);
		paging.setList(list);
		return paging;
	}

}
