/**
 * This class is generated by jOOQ
 */
package com.dao;

import java.sql.Date;
import java.util.ArrayList;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Configuration;
import org.jooq.DSLContext;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;
import org.springframework.util.StringUtils;

import com.domain.Order;
import com.util.Paging;

import sxj.db.tables.records.OrderRecord;
import static sxj.db.Tables.ORDER;


@Repository
public class OrderDao extends DAOImpl<OrderRecord, Order, Integer> {

	@Autowired
	private DSLContext dslContext;

	public OrderDao(Configuration configuration) {
		super(ORDER, Order.class, configuration);
	}

	@Override
	protected Integer getId(Order order) {
		return order.getId();
	}

	/****************************************************
	 * 下面是自定义方法
	 ***************************************************************/
	
	public Integer insertAndReturnId(Order order) {
		OrderRecord record = dslContext.newRecord(ORDER, order);
		record.insert();
		return record.getId();
	}
	
	public Order findOrderById(Integer id) {
		Condition condition = ORDER.ID.equal(id);
		return dslContext.select().from(ORDER).where(condition).fetchOneInto(Order.class);
	}
	
	/**
	 * 查询订单集合
	 * @param paging
	 * @return
	 */
	public Paging<Order> orderList(Paging<Order> paging) {
		List<Condition> conditions = new ArrayList<>();
		String orderField;
		if (StringUtils.hasText(paging.getKeyword())) {
			conditions.add(ORDER.NAME.like("%"+paging.getKeyword()+"%"));
		}
		conditions.add(ORDER.DELETED.eq(0));
		List<Order> list = dslContext.select().from(ORDER).where(conditions).orderBy(ORDER.DATE.desc())
				.limit(paging.offset(), paging.getPageSize()).fetchInto(Order.class);
		int totalCount = dslContext.fetchCount(dslContext.select().from(ORDER).where(conditions));
		
		paging.setTotalCount(totalCount);
		paging.setList(list);
		return paging;
	}

}
