/**
 * This class is generated by jOOQ
 */
package com.dao;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.DSLContext;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import sxj.db.tables.pojos.User;
import sxj.db.tables.records.UserRecord;

import static sxj.db.Tables.USER;;


@Repository
public class UserDao extends DAOImpl<UserRecord, sxj.db.tables.pojos.User, Integer> {
	@Autowired
	private DSLContext dslContext;

	public UserDao(Configuration configuration) {
		super(USER, User.class, configuration);
	}

	@Override
	protected Integer getId(User user) {
		// TODO Auto-generated method stub
		return user.getId();
	}
	/****************************************************
	 * 下面是自定义方法
	 ***************************************************************/

}
