/**
 * This class is generated by jOOQ
 */
package sxj.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import sxj.db.Keys;
import sxj.db.Test;
import sxj.db.tables.records.CourseRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Course extends TableImpl<CourseRecord> {

    private static final long serialVersionUID = 1765176012;

    /**
     * The reference instance of <code>test.course</code>
     */
    public static final Course COURSE = new Course();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CourseRecord> getRecordType() {
        return CourseRecord.class;
    }

    /**
     * The column <code>test.course.id</code>.
     */
    public final TableField<CourseRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>test.course.name</code>. 课程名称
     */
    public final TableField<CourseRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "课程名称");

    /**
     * The column <code>test.course.type</code>. 考试类型
     */
    public final TableField<CourseRecord, String> TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "考试类型");

    /**
     * The column <code>test.course.clazz_id</code>. 班级id
     */
    public final TableField<CourseRecord, Integer> CLAZZ_ID = createField("clazz_id", org.jooq.impl.SQLDataType.INTEGER, this, "班级id");

    /**
     * The column <code>test.course.weight</code>. 课程权重
     */
    public final TableField<CourseRecord, Double> WEIGHT = createField("weight", org.jooq.impl.SQLDataType.FLOAT, this, "课程权重");

    /**
     * The column <code>test.course.code</code>. 指标点代码
     */
    public final TableField<CourseRecord, String> CODE = createField("code", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "指标点代码");

    /**
     * The column <code>test.course.normal_percent</code>. 平时成绩百分比
     */
    public final TableField<CourseRecord, Double> NORMAL_PERCENT = createField("normal_percent", org.jooq.impl.SQLDataType.FLOAT, this, "平时成绩百分比");

    /**
     * The column <code>test.course.terminal_percent</code>. 期末成绩百分比
     */
    public final TableField<CourseRecord, Double> TERMINAL_PERCENT = createField("terminal_percent", org.jooq.impl.SQLDataType.FLOAT, this, "期末成绩百分比");

    /**
     * Create a <code>test.course</code> table reference
     */
    public Course() {
        this("course", null);
    }

    /**
     * Create an aliased <code>test.course</code> table reference
     */
    public Course(String alias) {
        this(alias, COURSE);
    }

    private Course(String alias, Table<CourseRecord> aliased) {
        this(alias, aliased, null);
    }

    private Course(String alias, Table<CourseRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Test.TEST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<CourseRecord, Integer> getIdentity() {
        return Keys.IDENTITY_COURSE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CourseRecord> getPrimaryKey() {
        return Keys.KEY_COURSE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CourseRecord>> getKeys() {
        return Arrays.<UniqueKey<CourseRecord>>asList(Keys.KEY_COURSE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Course as(String alias) {
        return new Course(alias, this);
    }

    /**
     * Rename this table
     */
    public Course rename(String name) {
        return new Course(name, null);
    }
}
