/**
 * This class is generated by jOOQ
 */
package sxj.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import sxj.db.Keys;
import sxj.db.Test;
import sxj.db.tables.records.FileRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class File extends TableImpl<FileRecord> {

    private static final long serialVersionUID = 678530289;

    /**
     * The reference instance of <code>test.file</code>
     */
    public static final File FILE = new File();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FileRecord> getRecordType() {
        return FileRecord.class;
    }

    /**
     * The column <code>test.file.id</code>.
     */
    public final TableField<FileRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>test.file.file_name</code>. 文件名
     */
    public final TableField<FileRecord, String> FILE_NAME = createField("file_name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "文件名");

    /**
     * The column <code>test.file.file_url</code>. 文件url
     */
    public final TableField<FileRecord, String> FILE_URL = createField("file_url", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "文件url");

    /**
     * The column <code>test.file.source</code>. 1.order，2.product
     */
    public final TableField<FileRecord, Integer> SOURCE = createField("source", org.jooq.impl.SQLDataType.INTEGER, this, "1.order，2.product");

    /**
     * The column <code>test.file.source_id</code>. 父id
     */
    public final TableField<FileRecord, Integer> SOURCE_ID = createField("source_id", org.jooq.impl.SQLDataType.INTEGER, this, "父id");

    /**
     * Create a <code>test.file</code> table reference
     */
    public File() {
        this("file", null);
    }

    /**
     * Create an aliased <code>test.file</code> table reference
     */
    public File(String alias) {
        this(alias, FILE);
    }

    private File(String alias, Table<FileRecord> aliased) {
        this(alias, aliased, null);
    }

    private File(String alias, Table<FileRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Test.TEST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<FileRecord, Integer> getIdentity() {
        return Keys.IDENTITY_FILE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<FileRecord> getPrimaryKey() {
        return Keys.KEY_FILE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<FileRecord>> getKeys() {
        return Arrays.<UniqueKey<FileRecord>>asList(Keys.KEY_FILE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public File as(String alias) {
        return new File(alias, this);
    }

    /**
     * Rename this table
     */
    public File rename(String name) {
        return new File(name, null);
    }
}
