/**
 * This class is generated by jOOQ
 */
package sxj.db;


import javax.annotation.Generated;

import sxj.db.tables.CodeMessage;
import sxj.db.tables.Order;
import sxj.db.tables.Product;


/**
 * Convenience access to all tables in test
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>test.code_message</code>.
     */
    public static final CodeMessage CODE_MESSAGE = sxj.db.tables.CodeMessage.CODE_MESSAGE;

    /**
     * The table <code>test.order</code>.
     */
    public static final Order ORDER = sxj.db.tables.Order.ORDER;

    /**
     * The table <code>test.product</code>.
     */
    public static final Product PRODUCT = sxj.db.tables.Product.PRODUCT;
}
